# Cloud Build configuration for Cosmic Guru Backend
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cosmic-guru-backend:$COMMIT_SHA', '.']
    dir: 'backend'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cosmic-guru-backend:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cosmic-guru-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cosmic-guru-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'PORT=8080,PYTHONUNBUFFERED=1'

# Store the built image
images:
  - 'gcr.io/$PROJECT_ID/cosmic-guru-backend:$COMMIT_SHA'

# Build options
options:
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'

# Substitutions (can be overridden at build time)
substitutions:
  _SERVICE_NAME: 'cosmic-guru-backend'
  _REGION: 'us-central1'
  _MEMORY: '1Gi'
  _CPU: '1'
  _MAX_INSTANCES: '10'