name: cosmic_guru
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pydantic=2.5.0
  - pytest=7.4.3
  - httpx=0.25.2
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - kerykeion==4.26.2
    - python-multipart==0.0.6
    - pytest-asyncio==0.21.1
    - timezonefinder==6.2.0
    - anthropic==0.57.1
    - python-dotenv==1.0.0
    - solarsystem==0.1.5